from esmvalcore._recipe import Recipe
from esmvalcore._config import (
    read_config_user_file,
)


def generate_variables(
        raw_recipe: dict,
        config_file: str,
        recipe_file: str,
        raw_variable: dict,
        raw_datasets: list
) -> list:
    """

    Parameters
    ----------
    raw_recipe
    config_file
    recipe_file
    raw_variable
    raw_datasets

    Returns
    -------
    list:
        generated by esmvalcore
            datasets from recipe.yml["datasets"]
            preprocessor1 from recipe.yml["preprocessors"]
            data params from recipe.yml["diagnostics"]
        [
            {
                'preprocessor': 'preprocessor1',
                'diagnostic': 'diagnostic1',
                'variable_group': 'ta',
                'short_name': 'ta',
                'standard_name': 'air_temperature',
                'long_name': 'Air Temperature',
                'units': 'K',

                'institute': ['CCCma'],
                'dataset': 'CanESM2',
                'project': 'CMIP5',
                'cmor_table': 'CMIP5',
                'mip': 'Amon',
                'exp': 'historical',
                'ensemble': 'r1i1p1',
                'frequency': 'mon',
                'modeling_realm': ['atmos'],

                'start_year': 1996,
                'end_year': 1998,

                'recipe_dataset_index': 0,
                'alias': 'CanESM2',

                # 'filename': (
                #     f'{work_dir}/preproc/diagnostic1/ta/CMIP5_CanESM2_Amon_historical_r1i1p1_ta_1996-1998.nc'
                # )  # 动态生成，没有用处
            },
            {
                'preprocessor': 'preprocessor1',
                'diagnostic': 'diagnostic1',
                'variable_group': 'ta',
                'short_name': 'ta',
                'standard_name': 'air_temperature',
                'long_name': 'Air Temperature',
                'units': 'K',

                'institute': ['LASG-CESS'],
                'dataset': 'FGOALS-g2',
                'project': 'CMIP5',
                'cmor_table': 'CMIP5',
                'mip': 'Amon',
                'exp': 'historical',
                'ensemble': 'r1i1p1',
                'frequency': 'mon',
                'modeling_realm': ['atmos'],

                'start_year': 1996,
                'end_year': 1998,

                'recipe_dataset_index': 1,
                'alias': 'FGOALS-g2',

                # 'filename': (
                #     f'{work_dir}/preproc/diagnostic1/ta/CMIP5_FGOALS-g2_Amon_historical_r1i1p1_ta_1996-1998.nc'
                # )  # 动态生成，没有用处
            }
        ]
    """
    config_user = read_config_user_file(config_file=config_file, recipe_name="recipe")

    recipe = Recipe(
        raw_recipe,
        config_user,
        initialize_tasks=False,
        recipe_file=recipe_file,
    )

    return recipe._initialize_variables(
        raw_variable=raw_variable,
        raw_datasets=raw_datasets,
    )
